### PR TITLE
Adding epel-release dependency.

### PR DESCRIPTION
**Pull request by vickumar1981**
- Adds missing dependency on epel-release package

### CODE REVIEW

**Comment by wenzong** [comment]
@vickumar1981 thanks for contribution

@imlazyone @tjoelsson maybe checkout this documentation https://aws.amazon.com/premiumsupport/knowledge-center/ec2-enable-epel/, no idea whether this PR works for amazon ec2, how about test it on amazon ec2 first?

**Comment by stuartwan** [comment]
Thanks for the PR, we'll do a test internally and once verified we'll merge this.

**Comment by stuartwan** [comment]
@wenzong thanks for the link. It mentioned that Amazon Linux already has EPEL installed.

> Amazon Linux – The EPEL repo is already installed on Amazon Linux, but it must be enabled by updating the epel.repo file. The following command illustrates use of the vim editor to update the epel.repo file ...

:+1:  to merge.

**Comment by tjoelsson** [comment]
:+1:

**Pull request merged**
