### PR TITLE
Update meta to allow deployment on Galaxy

### PR DESCRIPTION
**Pull request by tjoelsson**
- Add description
- Add tags
- Change Amazon Linux versions (these are used by other roles on Galaxy)

### CODE REVIEW

**Comment by tjoelsson** [comment]
@imlazyone @agirivera @wanleung please review

**Comment by stuartwan** [comment]
Did you test this?

**Comment by tjoelsson** [comment]
I successfully uploaded it from my fork.

**Comment by stuartwan** [comment]
:100:

**Comment by agirivera** [comment]
Looks good :+1:

**Comment by tjoelsson** [comment]
@imlazyone please merge

**Comment by stuartwan** [comment]
Re-imported to Galaxy.

**Pull request merged**
